./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 0.5 --lowr_thresh_factor 0.5 -o rec_0.5_0.5
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 1 --lowr_thresh_factor 0.5 -o rec_1.0_0.5
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 2 --lowr_thresh_factor 0.5 -o rec_2.0_0.5
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 3 --lowr_thresh_factor 0.5 -o rec_3_0.5
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 4 --lowr_thresh_factor 0.5 -o rec_4_0.5
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 0.5 --lowr_thresh_factor 1 -o rec_0.5_1.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 1 --lowr_thresh_factor 1 -o rec_1.0_1.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 2 --lowr_thresh_factor 1 -o rec_2.0_1.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 3 --lowr_thresh_factor 1 -o rec_3_1.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 4 --lowr_thresh_factor 1 -o rec_4_1.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 0.5 --lowr_thresh_factor 2 -o rec_0.5_2.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 1 --lowr_thresh_factor 2 -o rec_1.0_2.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 2 --lowr_thresh_factor 2 -o rec_2.0_2.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 3 --lowr_thresh_factor 2 -o rec_3_2.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 4 --lowr_thresh_factor 2 -o rec_4_2.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 0.5 --lowr_thresh_factor 3 -o rec_0.5_3.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 1 --lowr_thresh_factor 3 -o rec_1.0_3.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 2 --lowr_thresh_factor 3 -o rec_2.0_3.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 3 --lowr_thresh_factor 3 -o rec_3_3.0
./06_reconstruction_script.py -n 25 -p psf_fix_ave -m all --wave_thresh_factor 4 --lowr_thresh_factor 3 -o rec_4_3.0
